export const ErrorCodes = {
  SLOT_NOT_AVAILABLE: "SLOT_NOT_AVAILABLE",
  BOOKING_WINDOW_TOO_SHORT: "BOOKING_WINDOW_TOO_SHORT",
  CANCELLATION_WINDOW_TOO_SHORT: "CANCELLATION_WINDOW_TOO_SHORT",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
};

export function createAppError(status, code, message) {
  return { status, code, message };
}
